///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DataChecklistResponseData {
/*
{
  "id": 332,
  "asset_category_code": "GSU",
  "description": "GRAB SHIP UNLOADER",
  "check_name": "BOOM SYSTEM",
  "check_sub_name": "Cek Limit switch / Sensor",
  "type": "MKN",
  "number": 1,
  "category_local": "GSU",
  "status": 1
} 
*/

  int? id;
  String? assetCategoryCode;
  String? description;
  String? checkName;
  String? checkSubName;
  String? type;
  int? number;
  String? categoryLocal;
  int? status;

  DataChecklistResponseData({
    this.id,
    this.assetCategoryCode,
    this.description,
    this.checkName,
    this.checkSubName,
    this.type,
    this.number,
    this.categoryLocal,
    this.status,
  });
  DataChecklistResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    assetCategoryCode = json['asset_category_code']?.toString();
    description = json['description']?.toString();
    checkName = json['check_name']?.toString();
    checkSubName = json['check_sub_name']?.toString();
    type = json['type']?.toString();
    number = json['number']?.toInt();
    categoryLocal = json['category_local']?.toString();
    status = json['status']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['asset_category_code'] = assetCategoryCode;
    data['description'] = description;
    data['check_name'] = checkName;
    data['check_sub_name'] = checkSubName;
    data['type'] = type;
    data['number'] = number;
    data['category_local'] = categoryLocal;
    data['status'] = status;
    return data;
  }
}

class DataChecklistResponse {
/*
{
  "status": "S",
  "message": null,
  "data": [
    {
      "id": 332,
      "asset_category_code": "GSU",
      "description": "GRAB SHIP UNLOADER",
      "check_name": "BOOM SYSTEM",
      "check_sub_name": "Cek Limit switch / Sensor",
      "type": "MKN",
      "number": 1,
      "category_local": "GSU",
      "status": 1
    }
  ]
} 
*/

  String? status;
  String? message;
  List<DataChecklistResponseData?>? data;

  DataChecklistResponse({
    this.status,
    this.message,
    this.data,
  });
  DataChecklistResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DataChecklistResponseData>[];
      v.forEach((v) {
        arr0.add(DataChecklistResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
