///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ImageResponse {
/*
{
  "status": "S",
  "data": "sigap-api.erdata.id/temp/mobile/792b65f4-b465-486b-b00a-70bd697cc3dd/-20241031053507-652738750.png"
} 
*/

  String? status;
  String? data;

  ImageResponse({
    this.status,
    this.data,
  });
  ImageResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data;
    return data;
  }
}
