///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TerminalResponseData {
/*
{
  "id": 3,
  "code": "null",
  "name": "KANPUS SPTP"
} 
*/

  int? id;
  String? code;
  String? name;

  TerminalResponseData({
    this.id,
    this.code,
    this.name,
  });
  TerminalResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    code = json['code']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}

class TerminalResponse {
/*
{
  "status": "S",
  "message": "null",
  "data": [
    {
      "id": 3,
      "code": "null",
      "name": "KANPUS SPTP"
    }
  ]
} 
*/

  String? status;
  String? message;
  List<TerminalResponseData?>? data;

  TerminalResponse({
    this.status,
    this.message,
    this.data,
  });
  TerminalResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <TerminalResponseData>[];
      v.forEach((v) {
        arr0.add(TerminalResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
