///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DataTableCreateParamItem {
/*
{
  "id": 332,
  "asset_category_code": "GSU",
  "type": "MKN",
  "status": 0,
  "file_name": "catering1.png",
  "reason": "test"
} 
*/

  int? id;
  String? assetCategoryCode;
  String? type;
  int? status;
  String? fileName;
  String? reason;

  DataTableCreateParamItem({
    this.id,
    this.assetCategoryCode,
    this.type,
    this.status,
    this.fileName,
    this.reason,
  });
  DataTableCreateParamItem.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    assetCategoryCode = json['asset_category_code']?.toString();
    type = json['type']?.toString();
    status = json['status']?.toInt();
    fileName = json['file_name']?.toString();
    reason = json['reason']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['asset_category_code'] = assetCategoryCode;
    data['type'] = type;
    data['status'] = status;
    data['file_name'] = fileName;
    data['reason'] = reason;
    return data;
  }
}

class DataTableCreateParam {
/*
{
  "asset_id": 23,
  "asset_category_code": "GSU",
  "date_doc": "2024-10-30 14:57:50",
  "doc_type": "OPR",
  "item": [
    {
      "id": 332,
      "asset_category_code": "GSU",
      "type": "MKN",
      "status": 0,
      "file_name": "catering1.png",
      "reason": "test"
    }
  ]
} 
*/

  int? assetId;
  String? assetCategoryCode;
  String? dateDoc;
  String? docType;
  List<DataTableCreateParamItem?>? item;

  DataTableCreateParam({
    this.assetId,
    this.assetCategoryCode,
    this.dateDoc,
    this.docType,
    this.item,
  });
  DataTableCreateParam.fromJson(Map<String, dynamic> json) {
    assetId = json['asset_id']?.toInt();
    assetCategoryCode = json['asset_category_code']?.toString();
    dateDoc = json['date_doc']?.toString();
    docType = json['doc_type']?.toString();
    if (json['item'] != null) {
      final v = json['item'];
      final arr0 = <DataTableCreateParamItem>[];
      v.forEach((v) {
        arr0.add(DataTableCreateParamItem.fromJson(v));
      });
      item = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['asset_id'] = assetId;
    data['asset_category_code'] = assetCategoryCode;
    data['date_doc'] = dateDoc;
    data['doc_type'] = docType;
    if (item != null) {
      final v = item;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['item'] = arr0;
    }
    return data;
  }
}
